using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Text;

namespace Baseline.Core.Generators;

/// <summary>
/// Source generator that discovers content event handlers and generates
/// automatic registration code. Reduces boilerplate for event handling by 80%.
/// 
/// Usage:
/// [ContentItemEventHandler(typeof(BlogPost), ContentItemEventType.Create)]
/// public class BlogPostCreatedHandler : IContentItemEventHandler&lt;BlogPost&gt;
/// {
///     public Task HandleAsync(BlogPost item, ContentItemEventArgs args, CancellationToken ct) { ... }
/// }
/// 
/// Generated:
/// - Auto-registration in AddContentItemEventHandlers() extension
/// - Event subscription wiring
/// </summary>
[Generator]
public class EventHandlerRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register the attribute source
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("ContentItemEventHandlerAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8));
            ctx.AddSource("IContentItemEventHandler.g.cs", SourceText.From(InterfaceSource, Encoding.UTF8));
        });

        // Find all classes with [ContentItemEventHandler]
        var handlerDeclarations = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                "Baseline.Core.Generators.ContentItemEventHandlerAttribute",
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetHandlerInfo(ctx))
            .Where(static m => m is not null);

        // Combine with compilation
        var compilationAndHandlers = context.CompilationProvider
            .Combine(handlerDeclarations.Collect());

        // Generate registration code
        context.RegisterSourceOutput(compilationAndHandlers,
            static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static HandlerInfo? GetHandlerInfo(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol classSymbol)
            return null;

        var attribute = context.Attributes.FirstOrDefault();
        if (attribute == null)
            return null;

        // Get content type from attribute
        var contentType = attribute.ConstructorArguments.Length > 0
            ? attribute.ConstructorArguments[0].Value as INamedTypeSymbol
            : null;

        // Get event type
        var eventType = attribute.ConstructorArguments.Length > 1
            ? (int)(attribute.ConstructorArguments[1].Value ?? 0)
            : 0;

        if (contentType == null)
            return null;

        return new HandlerInfo(
            classSymbol.ToDisplayString(),
            classSymbol.Name,
            contentType.ToDisplayString(),
            contentType.Name,
            (ContentItemEventType)eventType,
            classSymbol.ContainingNamespace.ToDisplayString());
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<HandlerInfo?> handlers,
        SourceProductionContext context)
    {
        var validHandlers = handlers
            .Where(h => h is not null)
            .Cast<HandlerInfo>()
            .ToList();

        if (validHandlers.Count == 0)
            return;

        var source = GenerateRegistrationSource(validHandlers, compilation.AssemblyName ?? "Generated");
        context.AddSource("ContentItemEventHandlers.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateRegistrationSource(List<HandlerInfo> handlers, string assemblyName)
    {
        var sb = new StringBuilder();
        var namespaces = handlers
            .Select(h => h.Namespace)
            .Distinct()
            .OrderBy(n => n);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using CMS.ContentEngine;");
        sb.AppendLine("using CMS.DataEngine;");
        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }
        sb.AppendLine();

        var safeAssemblyName = MakeSafeIdentifier(assemblyName);
        sb.AppendLine($"namespace {safeAssemblyName}.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated content item event handler registration.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class ContentItemEventHandlerExtensions");
        sb.AppendLine("{");

        // Generate registration extension
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all discovered content item event handlers.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceCollection AddContentItemEventHandlers(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var handler in handlers)
        {
            sb.AppendLine($"        services.AddTransient<{handler.FullClassName}>();");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Generate event subscription helper
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Wires up event handlers to CMS events. Call this in application startup.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static void UseContentItemEventHandlers(this IServiceProvider serviceProvider)");
        sb.AppendLine("    {");

        foreach (var handler in handlers)
        {
            var eventMethod = handler.EventType switch
            {
                ContentItemEventType.Create => "Insert.After",
                ContentItemEventType.Update => "Update.After",
                ContentItemEventType.Delete => "Delete.After",
                ContentItemEventType.Publish => "Publish.Execute",
                _ => "Update.After"
            };

            sb.AppendLine($"        // {handler.ClassName} -> {handler.ContentTypeName}.{eventMethod}");
            sb.AppendLine($"        ContentItemEvents.{eventMethod}.Execute += async (sender, args) =>");
            sb.AppendLine("        {");
            sb.AppendLine($"            if (args.ContentTypeName == {handler.ContentTypeName}.CONTENT_TYPE_NAME)");
            sb.AppendLine("            {");
            sb.AppendLine($"                using var scope = serviceProvider.CreateScope();");
            sb.AppendLine($"                var handler = scope.ServiceProvider.GetRequiredService<{handler.FullClassName}>();");
            sb.AppendLine($"                await handler.HandleAsync(args, CancellationToken.None);");
            sb.AppendLine("            }");
            sb.AppendLine("        };");
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string MakeSafeIdentifier(string input)
    {
        return new string(input.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());
    }

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable
        
        namespace Baseline.Core.Generators;
        
        /// <summary>
        /// Marks a class as a content item event handler for automatic registration.
        /// </summary>
        [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple = true)]
        public sealed class ContentItemEventHandlerAttribute : System.Attribute
        {
            /// <summary>
            /// The content type this handler responds to.
            /// </summary>
            public System.Type ContentType { get; }
            
            /// <summary>
            /// The event type to handle.
            /// </summary>
            public ContentItemEventType EventType { get; }
        
            public ContentItemEventHandlerAttribute(System.Type contentType, ContentItemEventType eventType)
            {
                ContentType = contentType;
                EventType = eventType;
            }
        }
        
        /// <summary>
        /// Content item event types for handler registration.
        /// </summary>
        public enum ContentItemEventType
        {
            Create = 0,
            Update = 1,
            Delete = 2,
            Publish = 3
        }
        """;

    private const string InterfaceSource = """
        // <auto-generated/>
        #nullable enable
        
        namespace Baseline.Core.Generators;
        
        /// <summary>
        /// Interface for content item event handlers.
        /// </summary>
        public interface IContentItemEventHandler
        {
            /// <summary>
            /// Handles the content item event.
            /// </summary>
            System.Threading.Tasks.Task HandleAsync(
                CMS.ContentEngine.ContentItemEventArgsBase args,
                System.Threading.CancellationToken cancellationToken);
        }
        
        /// <summary>
        /// Typed interface for content item event handlers.
        /// </summary>
        public interface IContentItemEventHandler<T> : IContentItemEventHandler where T : class
        {
        }
        """;

    private sealed class HandlerInfo
    {
        public string FullClassName { get; }
        public string ClassName { get; }
        public string FullContentTypeName { get; }
        public string ContentTypeName { get; }
        public ContentItemEventType EventType { get; }
        public string Namespace { get; }

        public HandlerInfo(
            string fullClassName,
            string className,
            string fullContentTypeName,
            string contentTypeName,
            ContentItemEventType eventType,
            string @namespace)
        {
            FullClassName = fullClassName;
            ClassName = className;
            FullContentTypeName = fullContentTypeName;
            ContentTypeName = contentTypeName;
            EventType = eventType;
            Namespace = @namespace;
        }
    }

    private enum ContentItemEventType
    {
        Create = 0,
        Update = 1,
        Delete = 2,
        Publish = 3
    }
}
