using Baseline.Automation.Enums;

namespace Baseline.Automation.Email;

/// <summary>
/// Represents an email message generated by the automation engine.
/// Maps to CMS.Automation.AutomationEmail.
/// </summary>
public class AutomationEmailMessage
{
    /// <summary>Contact ID the email is for.</summary>
    public int ContactId { get; set; }

    /// <summary>Process ID that generated the email.</summary>
    public Guid ProcessId { get; set; }

    /// <summary>Step ID that generated the email.</summary>
    public Guid StepId { get; set; }

    /// <summary>Type of automation email.</summary>
    public AutomationEmailTypeEnum EmailType { get; set; } = AutomationEmailTypeEnum.ActionEmail;

    /// <summary>Email template name or identifier.</summary>
    public string TemplateName { get; set; } = "";

    /// <summary>Email subject (overrides template subject if set).</summary>
    public string? Subject { get; set; }

    /// <summary>Recipient email address (resolved from contact if not set).</summary>
    public string? RecipientEmail { get; set; }

    /// <summary>Recipient display name.</summary>
    public string? RecipientName { get; set; }

    /// <summary>Sender email address (uses default if not set).</summary>
    public string? SenderEmail { get; set; }

    /// <summary>Sender display name.</summary>
    public string? SenderName { get; set; }

    /// <summary>Custom data for template macro resolution.</summary>
    public Dictionary<string, string> CustomData { get; set; } = new();

    /// <summary>Whether this email has been sent.</summary>
    public bool IsSent { get; set; }

    /// <summary>Error message if sending failed.</summary>
    public string? ErrorMessage { get; set; }

    /// <summary>When the email was queued.</summary>
    public DateTimeOffset QueuedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>When the email was sent.</summary>
    public DateTimeOffset? SentAt { get; set; }
}
